"""
rag.py
──────
Retrieval-Augmented Generation orchestration layer.

Works with the real recipes_small.json dataset via recipe_loader.py.
The normalised schema provides: id, name, ingredients, steps, dietary,
cuisine, cook_time_minutes, calories, difficulty, servings.

Fields NOT in the dataset (substitutions, waste tips, nutrition macros,
missing ingredients) are entirely generated by IBM Granite at query time.

Public API:
  rag_pipeline.recommend()          → full AI recipe card
  rag_pipeline.get_substitutions()  → ingredient swap suggestions
  rag_pipeline.get_shopping_list()  → missing items + shopping list
  rag_pipeline.get_leftover_ideas() → creative leftover recipe ideas
  rag_pipeline.detect_missing()     → ingredient coverage for a recipe
"""

import logging
from typing import Optional

from granite import (
    generate_leftover_suggestions,
    generate_recipe_response,
    generate_shopping_list,
    generate_substitutions,
)
from recipe_loader import filter_recipes, get_recipe_by_id, load_recipes
from vector_store import vector_store

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# RAG Pipeline
# ─────────────────────────────────────────────────────────────────────────────

class RAGPipeline:
    """
    Orchestrates the full RAG flow for every user request:
        User Ingredients
              ↓
        Build semantic query string
              ↓
        SentenceTransformer embed → 384-dim vector
              ↓
        ChromaDB cosine similarity search → top-K recipe IDs + metadata
              ↓
        Hydrate: join vector-store results with full recipe JSON
              ↓
        Construct augmented prompt (context + user ingredients)
              ↓
        IBM Granite generation
              ↓
        Return structured response to Flask
    """

    def __init__(self):
        self._ready = False

    def initialize(self) -> None:
        """Initialise the vector store (loads + embeds all recipes once)."""
        logger.info("Initialising RAG pipeline...")
        vector_store.initialize()
        self._ready = True
        logger.info("RAG pipeline ready.")

    # ── Core recommendation ───────────────────────────────────────────────────

    def recommend(
        self,
        ingredients: list[str],
        cuisine_filter: Optional[str] = None,
        dietary_filter: Optional[list[str]] = None,
        top_k: int = 5,
    ) -> dict:
        """
        Full RAG recommendation.

        Steps:
          1. Build semantic query from ingredients + filters
          2. Retrieve top-K from ChromaDB
          3. Hydrate with full recipe data from recipes_small.json
          4. Send to IBM Granite
          5. Return structured response

        Returns:
            {
              generated_response : str,          # IBM Granite output
              retrieved_recipes  : list[dict],   # top-K with full_recipe key
              query_ingredients  : list[str],
              filters_applied    : dict,
            }
        """
        self._assert_ready()

        query = _build_ingredient_query(ingredients, cuisine_filter, dietary_filter)
        logger.info("RAG query: %.120s", query)

        retrieved = vector_store.query(
            query_text=query,
            top_k=top_k,
            cuisine_filter=cuisine_filter,
            dietary_filter=dietary_filter,
        )
        logger.info("Retrieved %d recipes from ChromaDB.", len(retrieved))

        hydrated = _hydrate_recipes(retrieved)

        generated = generate_recipe_response(
            user_ingredients=ingredients,
            retrieved_recipes=hydrated,
            cuisine_filter=cuisine_filter,
            dietary_filter=dietary_filter,
        )

        return {
            "generated_response": generated,
            "retrieved_recipes":  hydrated,
            "query_ingredients":  ingredients,
            "filters_applied": {
                "cuisine": cuisine_filter,
                "dietary": dietary_filter,
            },
        }

    # ── Ingredient substitutions ──────────────────────────────────────────────

    def get_substitutions(
        self,
        ingredient: str,
        recipe_name: str,
        dietary_constraints: Optional[list[str]] = None,
    ) -> dict:
        """
        Returns:
            { ingredient, recipe_name, suggestions (str from Granite) }
        """
        self._assert_ready()

        suggestions = generate_substitutions(
            ingredient=ingredient,
            recipe_name=recipe_name,
            dietary_constraints=dietary_constraints,
        )
        return {
            "ingredient":  ingredient,
            "recipe_name": recipe_name,
            "suggestions": suggestions,
        }

    # ── Shopping list ─────────────────────────────────────────────────────────

    def get_shopping_list(
        self,
        recipe_id: str,
        available_ingredients: list[str],
    ) -> dict:
        """
        Detects missing ingredients via fuzzy token matching, then asks
        Granite to format a categorised shopping list.

        Returns:
            {
              recipe_name, recipe_ingredients, available_ingredients,
              missing_ingredients, shopping_list (str)
            }
        """
        self._assert_ready()

        recipe = get_recipe_by_id(recipe_id)
        if not recipe:
            raise ValueError(f"Recipe id '{recipe_id}' not found in dataset.")

        recipe_ingredients = recipe.get("ingredients", [])
        missing = detect_missing_ingredients(recipe_ingredients, available_ingredients)

        shopping_list_text = generate_shopping_list(
            recipe_name=recipe["name"],
            recipe_ingredients=recipe_ingredients,
            available_ingredients=available_ingredients,
        )

        return {
            "recipe_name":           recipe["name"],
            "recipe_ingredients":    recipe_ingredients,
            "available_ingredients": available_ingredients,
            "missing_ingredients":   missing,
            "shopping_list":         shopping_list_text,
        }

    # ── Leftover ideas ────────────────────────────────────────────────────────

    def get_leftover_ideas(
        self,
        leftover_ingredients: list[str],
        cuisine_preference: Optional[str] = None,
    ) -> dict:
        """
        Returns:
            {
              leftover_ingredients,
              suggestions (str from Granite),
              similar_recipes (top-3 from vector store)
            }
        """
        self._assert_ready()

        similar = vector_store.query(
            query_text=" ".join(leftover_ingredients),
            top_k=3,
            cuisine_filter=cuisine_preference,
        )

        suggestions = generate_leftover_suggestions(
            leftover_ingredients=leftover_ingredients,
            cuisine_preference=cuisine_preference,
        )

        return {
            "leftover_ingredients": leftover_ingredients,
            "suggestions":          suggestions,
            "similar_recipes":      _hydrate_recipes(similar),
        }

    # ── Missing ingredient detection ──────────────────────────────────────────

    def detect_missing(
        self,
        recipe_id: str,
        available_ingredients: list[str],
    ) -> dict:
        """
        Returns:
            { recipe_name, have (list), missing (list), coverage_percent }
        """
        self._assert_ready()

        recipe = get_recipe_by_id(recipe_id)
        if not recipe:
            raise ValueError(f"Recipe id '{recipe_id}' not found.")

        recipe_ingredients = recipe.get("ingredients", [])
        missing  = detect_missing_ingredients(recipe_ingredients, available_ingredients)
        have     = [i for i in recipe_ingredients if i not in missing]
        coverage = round(len(have) / max(len(recipe_ingredients), 1) * 100, 1)

        return {
            "recipe_name":      recipe["name"],
            "have":             have,
            "missing":          missing,
            "coverage_percent": coverage,
        }

    # ── Internal ──────────────────────────────────────────────────────────────

    def _assert_ready(self) -> None:
        if not self._ready:
            raise RuntimeError("RAGPipeline.initialize() must be called first.")


# ─────────────────────────────────────────────────────────────────────────────
# Module-level singleton — imported by app.py
# ─────────────────────────────────────────────────────────────────────────────
rag_pipeline = RAGPipeline()


# ─────────────────────────────────────────────────────────────────────────────
# Pure helper functions
# ─────────────────────────────────────────────────────────────────────────────

def _build_ingredient_query(
    ingredients: list[str],
    cuisine: Optional[str],
    dietary: Optional[list[str]],
) -> str:
    """
    Build a rich semantic query string.
    Packing cuisine and dietary preference into the query text improves
    retrieval accuracy beyond metadata filtering alone.
    """
    parts = [f"Recipe using: {', '.join(ingredients)}."]
    if cuisine:
        parts.append(f"Cuisine: {cuisine}.")
    if dietary:
        parts.append(f"Dietary: {', '.join(dietary)}.")
    return " ".join(parts)


def _hydrate_recipes(retrieved: list[dict]) -> list[dict]:
    """
    Enrich vector-store results with full recipe data from recipes_small.json.
    The vector store keeps only metadata; full steps, ingredients, and
    normalised fields live in the JSON source of truth.
    """
    hydrated = []
    for item in retrieved:
        full = get_recipe_by_id(item["id"])
        if full:
            item["full_recipe"] = full
        hydrated.append(item)
    return hydrated


def detect_missing_ingredients(
    recipe_ingredients: list[str],
    available_ingredients: list[str],
) -> list[str]:
    """
    Fuzzy token-overlap matching.

    Uses lowercase word tokens so "boneless skinless chicken breast" matches
    when the user has "chicken". Strips common quantity/unit words before
    comparing so "2 tbsp olive oil" matches "olive oil".

    Returns the list of recipe_ingredients NOT covered by available_ingredients.
    """
    available_tokens: set[str] = set()
    for ing in available_ingredients:
        available_tokens.update(_core_tokens(ing))

    missing = []
    for recipe_ing in recipe_ingredients:
        core = _core_tokens(recipe_ing)
        if not any(tok in available_tokens for tok in core):
            missing.append(recipe_ing)

    return missing


# Quantity/unit/adjective words to strip before matching
_STOP_TOKENS = {
    "g", "kg", "ml", "l", "lb", "oz", "cup", "cups", "tbsp", "tsp",
    "tablespoon", "tablespoons", "teaspoon", "teaspoons",
    "large", "small", "medium", "fresh", "dried", "whole", "ground",
    "chopped", "diced", "sliced", "minced", "grated", "shredded",
    "peeled", "seeded", "boneless", "skinless", "lean",
    "optional", "to", "taste", "for", "of", "and", "or",
    "a", "an", "the", "1", "2", "3", "4", "0.5", "0.25",
    "inch", "cloves", "clove", "can", "package", "pkg",
}


def _core_tokens(ingredient: str) -> list[str]:
    """
    Extract meaningful tokens from an ingredient string after stripping
    quantity/unit/adjective noise words.
    """
    words = ingredient.lower().replace("-", " ").split()
    core  = [w.strip("(),./") for w in words if w.strip("(),./") not in _STOP_TOKENS]
    return core if core else [ingredient.lower().strip()]
